CREATE TABLE person
(
    id       bigint generated by default as identity primary key,
    username varchar not null unique,
    email    varchar not null unique,
    password varchar not null,
    role     varchar not null,
    enable   boolean default false
);
UPDATE person set role='ROLE_ADMIN' where id=3;

CREATE TABLE Post
(
    id             bigint generated by default as identity primary key,
    owner_username varchar references person (username) not null,
    title          varchar                              not null,
    description    varchar                              not null,
    views          int       default 0,
    photo_url      varchar                              not null,
    created_at     timestamp default current_timestamp,
    category       varchar                              not null
);
DROP TABLE Photo_like;
DROP TABLE Comment;
DROP TABLE Post;


CREATE TABLE Comment
(
    id              bigint generated by default as identity primary key,
    post_id         bigint references post (id) on delete cascade not null,
    person_username varchar references person (username)          not null,
    description     text                                          not null,
    created_at      timestamp default current_timestamp
);

CREATE TABLE Photo_like
(
    id              bigint generated by default as identity primary key,
    post_id         bigint references post (id) on delete cascade not null,
    person_username varchar references person (username)          not null
);

DROP TABLE Photo_like, Comment;
DROP TABLE Post, Person;
TRUNCATE TABLE person;
DELETE
from person
where id = 2;

CREATE TABLE Activation
(
    id       bigint generated by default as identity primary key,
    key      varchar                              not null,
    username varchar references person (username) not null
);